# Generated by Django 4.2.5 on 2023-10-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='user_ID',
        ),
    ]
