# Generated by Django 4.2.5 on 2023-10-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrInfo', '0002_rename_user_id_userinfo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_ID',
            new_name='id_user',
        ),
    ]
