# Generated by Django 4.2.5 on 2023-10-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_rename_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
