# Generated by Django 4.2.5 on 2023-10-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserMusicList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdb',
            name='videoId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
