# Generated by Django 4.2.5 on 2023-10-10 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserMusicList', '0002_musicdb_videoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclist',
            name='video_Views',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
