# Generated by Django 4.2.5 on 2023-10-18 00:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserMusicList', '0004_alter_list_list_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=75, null=True)),
                ('channel_name', models.CharField(max_length=50, null=True)),
                ('channel_Thumb', models.URLField(max_length=254, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='SingerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Singer_Views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserMusicList.singer')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserMusicList.musicdb')),
            ],
        ),
        migrations.AddField(
            model_name='singer',
            name='inSingerList',
            field=models.ManyToManyField(through='UserMusicList.SingerList', to='UserMusicList.musicdb'),
        ),
    ]
